[package]
name = "webapp_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
btleplug = "0.11.7"
futures-util = "0.3.31"
rust-crypto = "0.2.36"
tokio = { version = "1.43.0", features = ["full"] }
uuid = "1.11.1"
